import { authenticateRequest } from "@/lib/authGuard";
import { corsResponse, handleCORSPreflight, CORS_HEADERS } from "@/lib/cors";

/**
 * GET /api/auth/mfa
 * Dummy endpoint for MFA Enrollment/Status.
 */
export async function GET(request) {
  try {
    const auth = await authenticateRequest(request);
    if (auth.error) {
      return corsResponse({ error: "No active session found" }, 401);
    }

    return new Response(JSON.stringify({ 
      is_mfa_enabled: false,
      message: "Multi-Factor Authentication (MFA) is disabled."
    }), { status: 200, headers: CORS_HEADERS });
  } catch (error) {
    console.error("🔥 BACKEND CRASH ERROR:", error);
    return corsResponse({ success: false, error: error.message || "Unknown error" }, 500);
  }
}

/**
 * POST /api/auth/mfa
 * Dummy endpoint to Simulate MFA Setup (returns "Feature Coming Soon").
 */
export async function POST(request) {
  try {
    const auth = await authenticateRequest(request);
    if (auth.error) {
      return corsResponse({ error: "No active session found" }, 401);
    }

    return new Response(JSON.stringify({ 
      success: false,
      is_mock: true,
      message: "MFA Feature Coming Soon",
      mock_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=fortigrc-mfa-mock-setup",
      mock_secret: "MOCKMFAFEATURECOMINGSOON123",
      instruction: "This is a demo environment. Real Time-based One-Time Passwords (TOTP) will be generated by Supabase Auth in production."
    }), { status: 200, headers: CORS_HEADERS });
  } catch (error) {
    console.error("🔥 BACKEND CRASH ERROR:", error);
    return corsResponse({ success: false, error: error.message || "Unknown error" }, 500);
  }
}

export function OPTIONS() {
  return handleCORSPreflight();
}
